### ISSUE TITLE
Bad parse

### ISSUE THREAD

**Issue by jvonmitchell** [isaacs/node-url#1]
Hi,

I have a condition where url doesn't preform what would be the best behavior.

Lets say we do url.parse('vimque.com:8080/?somedata');

A typical browser will know what to do with that url and so do many node modules.  Obviously the port is 8080 and the host is vimque.com but we end up with 8080 as the host.

That seems pretty reasonable because the format is ambiguous but the idea of a module is to do some action more consistently and more correctly for all the edge cases than if the programmer just built something on the fly.  Browsers seem to be able to break that url down so I think we could make it smart enough.

**Comment by isaacs** [comment]
You need to specify a protocol.  Since it handles generic URLs like `mailto:user@host` and `git://blah` and `ssh://host` and `xmpp:username@host`, it can't assume `http` like a web browser does.
