### ISSUE TITLE
Using "exports" without defining it.

### ISSUE THREAD

**Issue by reggi** [isaacs/node-url#2]
Not sure if the "exports" variable is a global within nodejs. I just installed this with Bower and I'm using it in the browser and it's not working. I mean "node" is in the title. But it would still be cool to use this library in the browser.

**Comment by vhmth** [comment]
@reggi that is the CommonJS way of exporting a module (well syntactically that's not entirely correct as of ES6 - the newer Javascript revision). If you wish to use this module as-is, you would have to use a CommonJS module loader like Browserify. There are other module loaders based on different specifications other than CommonJS (such as AMD - most popularly implemented by RequireJS). You may see code like this in libraries:

```
(function () {
  // "this" context is now either a node global context or window context

  var libraryObject = { ...definitions... };

  if (typeof define === 'function' && define.amd) {
    // search for AMD loading context
    define('name-of-library', [], function () { return libraryObject; });
  } else {
    // export on the node "exports" object or "window" context
    (this.exports || this).libraryObject = libraryObject;
  }
}.call(this, window));
```

**Comment by isaacs** [comment]
Check out [browserify](http://npm.im/browserify) or [webpack](http://npm.im/webpack)
